const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store=(k,v)=>localStorage.setItem(k,JSON.stringify(v)), load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const state={character:'marquis',last:'',posts:load('courtisanPosts',[]),votes:load('courtisanVotes',0),contacts:load('courtisanContacts',[])};
const intros={marquis:["Monsieur,","Mon cher,","Permettez-moi de vous faire observer que"],duchesse:["Cher ami,","Je crains de devoir constater que","Il m'est pénible de relever que"],roi:["Notre volonté est que","Que chacun sache ceci :","La Cour retiendra que"],diplomate:["Avec tout le respect qui vous est dû,","Permettez-moi, avec la plus grande courtoisie, de préciser que","Je me dois de vous répondre que"],mousquetaire:["Par ma foi,","Monsieur, foi de gentilhomme,","Je vous le dis sans détour :"],seducteur:["Mon tendre ami,","Votre grâce m'oblige à vous confier que","Si mon cœur avait voix au chapitre,"]};
const endings={marquis:["; l'élégance commande parfois de savoir s'arrêter.","; je vous laisse le loisir d'en méditer l'évidence.","; voilà de quoi épargner à chacun une agitation superflue."],duchesse:["; certaines évidences gagnent à être comprises avant d'être répétées.","; le silence vous siérait peut-être avec un charme inattendu.","; la délicatesse consiste aussi à reconnaître le moment de se retirer."],roi:[". Qu'il en soit ainsi.",". Notre décision ne requiert point davantage de commentaire.",". La chose est entendue."],diplomate:["; je ne doute point que votre jugement saura en apprécier la mesure.","; cette solution me paraît préserver l'honneur de chacun.","; j'espère que nous pourrons en demeurer là avec grâce."],mousquetaire:["; point n'est besoin d'un duel pour comprendre cela.","; gardons nos lames au fourreau et notre bon sens à portée de main.","; je préfère la franchise au vacarme."],seducteur:["; encore faudrait-il que votre impatience me laisse le temps de vous regretter.","; vous gagneriez presque à me faire attendre davantage.","; votre empressement pourrait finir par me flatter."]};
const pick=a=>a[Math.floor(Math.random()*a.length)];
function courtify(text,opt={}){let t=(text||'').trim();if(!t)return"Votre silence est d'une noblesse admirable, mais il me laisse peu de matière à orner.";const ch=opt.character||state.character,sar=+($('#sarcasm')?.value||60)+(opt.sharp||0),aro=+($('#arrogance')?.value||50)+(opt.royal||0),rom=+($('#romance')?.value||20);const reps=[[/\bsalut\b/gi,"mes hommages"],[/\bbonjour\b/gi,"je vous salue avec déférence"],[/\btu me saoules\b/gi,"vous éprouvez ma patience avec une constance remarquable"],[/\bj'en ai marre\b/gi,"ma patience touche à ses dernières grâces"],[/\btu racontes n'importe quoi\b/gi,"vos paroles ont pris congé de la vérité avec une aisance remarquable"],[/\bt'es nul\b/gi,"votre talent semble aujourd'hui s'être accordé congé"],[/\bferme[- ]?la\b/gi,"épargnez-nous, je vous prie, de plus amples paroles"],[/\barrête\b/gi,"daignez cesser"],[/\brelancer\b/gi,"me rappeler avec tant d'empressement"],[/\bje veux\b/gi,"je souhaite"],[/\bje peux pas\b/gi,"il ne m'est guère possible de"],[/\bpas envie\b/gi,"je ne ressens nulle inclination"],[/\bmerci\b/gi,"recevez ma gratitude"],[/\bdésolé\b/gi,"je vous prie d'excuser mon manquement"],[/\bnon\b/gi,"il ne saurait en être question"],[/\boui\b/gi,"j'y consens volontiers"],[/\btu\b/gi,"vous"],[/\btoi\b/gi,"vous"],[/\bton\b/gi,"votre"],[/\bta\b/gi,"votre"],[/\btes\b/gi,"vos"]];reps.forEach(([r,v])=>t=t.replace(r,v));t=t.charAt(0).toLowerCase()+t.slice(1).replace(/[.!?]+$/,'');if(sar>72)t+=", prouesse dont la Cour elle-même peinerait à dissimuler son étonnement";if(aro>75&&ch!=='roi')t+=", quoique certains jugements eussent gagné à solliciter audience avant de conclure";if(rom>68)t+=", quoique votre audace possède un charme auquel il m'est difficile de demeurer insensible";return`${pick(intros[ch])} ${t}${pick(endings[ch])}`}
function reverse(t){const s=t.toLowerCase();if(s.includes('patience'))return'En français moderne : « Tu m’agaces / arrête d’insister. »';if(s.includes('silence'))return'En français moderne : « Tais-toi, mais avec élégance. »';if(s.includes('ne saurait'))return'En français moderne : « Non. »';if(s.includes('consens'))return'En français moderne : « Oui. »';return'En français moderne : même idée, avec beaucoup moins de dorures.'}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden');if(b.dataset.view==='court')renderFeed();if(b.dataset.view==='duels')renderDuel();if(b.dataset.view==='share')updateShare()});
$$('.char').forEach(b=>b.onclick=()=>{$$('.char').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.character=b.dataset.char});['elegance','sarcasm','arrogance','romance'].forEach(id=>$('#'+id).oninput=e=>$('#'+id+'V').textContent=e.target.value);
function render(extra={}){state.last=courtify($('#inputText').value,{character:state.character,...extra});$('#result').textContent=state.last;$('#translation').textContent=reverse(state.last);$('#translation').classList.remove('hidden');updateShare()}
$('#transform').onclick=()=>render();$('#humiliate').onclick=()=>render({sharp:32});$('#royal').onclick=()=>render({royal:28});$('#sharp').onclick=()=>render({sharp:22});$('#surprise').onclick=()=>{const s=["Tu me saoules, arrête de me relancer.","Je ne suis pas d'accord avec toi.","Tu racontes n'importe quoi.","Je viens ce soir si j'ai le temps.","Merci mais je n'ai pas envie."];$('#inputText').value=pick(s);render()};$('#copy').onclick=async()=>{await copyText(state.last||$('#result').textContent);toast('Répartie copiée ⚜')};
$('#publish').onclick=()=>{if(!state.last)return toast('Générez d’abord une répartie.');state.posts.unshift({id:Date.now(),text:state.last,char:state.character,votes:0,created:new Date().toISOString()});store('courtisanPosts',state.posts);toast('Publiée dans La Cour ⚜')};
$('#convTransform').onclick=()=>{const raw=$('#convInput').value.trim();if(!raw)return;$('#convResult').textContent=raw.split(/\n+/).map((line,i)=>{const m=line.match(/^([^:]{1,30}):\s*(.*)$/),speaker=m?m[1]:(i%2?'Interlocuteur':'Moi'),txt=m?m[2]:line,ch=(speaker.toLowerCase().includes('moi')||i%2===0)?$('#meRole').value:$('#otherRole').value;return`${speaker} : ${courtify(txt,{character:ch})}`}).join('\n\n')};
function titleFor(v){if(v>=50)return'Prince de la répartie';if(v>=25)return'Duc de la Cour';if(v>=12)return'Marquis';if(v>=6)return'Chevalier';if(v>=2)return'Écuyer';return'Roturier distingué'}
function renderFeed(){const f=$('#feed');const total=state.posts.reduce((a,p)=>a+p.votes,0);$('#rank').innerHTML=`<b>${titleFor(total)}</b><br><small>${total} ⚜ reçus au total</small>`;if(!state.posts.length){f.innerHTML='<div class="empty">Aucune répartie publiée. Publiez-en une depuis le Générateur.</div>';return}f.innerHTML=state.posts.map((p,i)=>`<article class="post"><div class="quote">“${escapeHtml(p.text)}”</div><div class="postbar"><span>${escapeHtml(p.char)} · ${new Date(p.created).toLocaleDateString('fr-FR')}</span><button class="vote" data-vote="${i}">⚜ ${p.votes}</button></div></article>`).join('');$$('[data-vote]').forEach(b=>b.onclick=()=>{state.posts[+b.dataset.vote].votes++;store('courtisanPosts',state.posts);renderFeed()})}
function renderDuel(){const samples=["Tu peux arrêter de me relancer ?","Je ne veux pas venir.","Tu racontes n'importe quoi.","Je n'ai pas le temps aujourd'hui.","Pourquoi tu réponds jamais ?"],seed=pick(samples),a=courtify(seed,{character:'marquis',sharp:20}),b=courtify(seed,{character:'duchesse',sharp:18});$('#duelBox').innerHTML=`<div class="card"><div class="label">Marquis</div><div class="quote">${escapeHtml(a)}</div><div class="actions"><button class="action ghost duelvote">⚜ Voter</button></div></div><div class="vs">VS</div><div class="card"><div class="label">Duchesse</div><div class="quote">${escapeHtml(b)}</div><div class="actions"><button class="action ghost duelvote">⚜ Voter</button></div></div>`;$$('.duelvote').forEach(x=>x.onclick=()=>{x.textContent='⚜ Vote enregistré';x.disabled=true})}$('#newDuel').onclick=renderDuel;
function updateShare(){const q=state.last||'Générez une répartie puis transformez-la en carte partageable.';$('#shareQuote').textContent=q}async function copyText(t){try{await navigator.clipboard.writeText(t)}catch{const ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}}$('#copyCard').onclick=()=>{copyText(state.last||$('#shareQuote').textContent);toast('Texte copié')};$('#nativeShare').onclick=async()=>{const text=state.last||$('#shareQuote').textContent;if(navigator.share){try{await navigator.share({title:'Le Courtisan',text})}catch{}}else{await copyText(text);toast('Partage natif indisponible : texte copié')}};
function renderContacts(){const el=$('#contacts');if(!state.contacts.length){el.innerHTML='<div class="hint">Aucun profil de contact.</div>';return}el.innerHTML=state.contacts.map((c,i)=>`<div class="card" style="margin-bottom:8px"><b>${escapeHtml(c.name)}</b> — ${escapeHtml(c.role)} <button class="action ghost" style="float:right;padding:5px 8px" data-del="${i}">Supprimer</button></div>`).join('');$$('[data-del]').forEach(b=>b.onclick=()=>{state.contacts.splice(+b.dataset.del,1);store('courtisanContacts',state.contacts);renderContacts()})}$('#saveContact').onclick=()=>{const n=$('#contactName').value.trim();if(!n)return;state.contacts.push({name:n,role:$('#contactRole').value});store('courtisanContacts',state.contacts);$('#contactName').value='';renderContacts();toast('Profil enregistré')};renderContacts();
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
/* PRODUCTION: remplacer courtify() par un POST /api/generate vers un backend. Ne jamais exposer une clé IA dans le navigateur.
   Webhooks prévus: /api/webhooks/sms, /api/webhooks/whatsapp, /api/webhooks/meta.
   Chaque webhook doit vérifier la signature du fournisseur, classifier les risques, appliquer le profil contact, puis envoyer seulement si le mode et les garde-fous l'autorisent. */
